#!/bin/bash

# Setup script for Triage Keyboard Extension
# This script provides instructions for adding the keyboard extension to your Xcode project

echo "🚀 Triage Keyboard Extension Setup Instructions"
echo "=============================================="
echo ""
echo "To add the keyboard extension to your Xcode project, follow these steps:"
echo ""
echo "1. Open your triage.xcodeproj in Xcode"
echo ""
echo "2. Add a new target:"
echo "   - Click on your project name in the navigator"
echo "   - Click the '+' button at the bottom of the targets list"
echo "   - Choose 'iOS' → 'Application Extension' → 'Custom Keyboard Extension'"
echo "   - Name it 'TriageKeyboard'"
echo "   - Set the bundle identifier to: com.yourcompany.triage.TriageKeyboard"
echo ""
echo "3. Replace the generated files with our custom implementation:"
echo "   - Delete the generated KeyboardViewController.swift"
echo "   - Add the KeyboardViewController.swift from the TriageKeyboard folder"
echo "   - Replace the Info.plist with our custom one"
echo ""
echo "4. Add App Groups capability:"
echo "   - Select your main app target"
echo "   - Go to 'Signing & Capabilities'"
echo "   - Add 'App Groups' capability"
echo "   - Add group: group.com.yourcompany.triage"
echo "   - Repeat for the TriageKeyboard target"
echo ""
echo "5. Build and run the project"
echo ""
echo "6. Enable the keyboard on your device:"
echo "   - Go to Settings → General → Keyboard → Keyboards"
echo "   - Tap 'Add New Keyboard'"
echo "   - Select 'Triage Parser'"
echo "   - Enable 'Allow Full Access'"
echo ""
echo "✅ Your keyboard extension is now ready to use!"
echo ""
echo "🚀 NEW: Quick Replies Feature!"
echo "- Set up quick replies in Settings → Quick Replies"
echo "- Access them instantly from the keyboard extension"
echo "- Tap 'Quick Replies' button to show/hide reply options"
echo ""
echo "Testing the parsing functionality:"
echo "- Open any app with text input (Notes, Messages, etc.)"
echo "- Switch to the Triage Parser keyboard"
echo "- Use Quick Replies for instant responses"
echo "- Or paste a customer message in this format:"
echo "  name: John Doe"
echo "  email: john@example.com"
echo "  address: 123 Main Street"
echo "  phone: +1234567890"
echo "  order: 2x Coffee"
echo "- Tap 'Parse & Save'"
echo "- The parsed data will appear in your main Triage app"
echo ""
